  
logging:
  level:
    com.example.demo: INFO
    
spring:
  datasource:
    tomcat:
      test-on-borrow: true
      test-on-connect: true
      validation-query: select version();
      validation-query-timeout: 5000
      test-on-return: true
    url: jdbc:mysql://localhost/Loans
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
